### ISSUE TITLE
No In App Purchasing Alert Bug

### ISSUE THREAD

**Issue by antgiant** [ItsCalebJones/SpaceLaunchNow-Flutter#11]
I have in app purchasing disabled to prevent my kids from getting into trouble with real money. Unfortunately, that makes using this app really painful to use as it pops up a notification every few seconds that I have in app purchases disabled. For instance I just shared a launch alert by text and had to click ok on the alert three times while composing a one sentence text.
Can you please turn off the barrage of modal alerts? Thank you

**Comment by ItsCalebJones** [comment]
That's very odd - i'm not quite sure what's causing that. I do a check to see if any IAP's have been made before showing ads. I suppose any check to see if IAP's have been made is whats triggering the modal. 

I'll look into it.

**Comment by antgiant** [comment]
Thank you!
I think that is it. I just realized that the modal even blocks switching apps so it must be a system level modal.

Perhaps this is helpful?

https://stackoverflow.com/questions/25447513/ios-how-to-check-if-in-app-purchase-enabled#25447916

**Comment by ItsCalebJones** [comment]
Might be fixed by https://github.com/ItsCalebJones/SpaceLaunchNow-Flutter/commit/36a0862cf2a05a76f403cac292489d70e1e686ad I will have to test it when it gets built and published.

**Comment by antgiant** [comment]
Just got the update and I am no longer getting IAP pop-ups all the time!

Thank you so much!

**Comment by ItsCalebJones** [comment]
Great to hear https://github.com/ItsCalebJones/SpaceLaunchNow-Flutter/commit/36a0862cf2a05a76f403cac292489d70e1e686ad fixed it.

**Comment by antgiant** [comment]
FYI that this bug has returned. :-(
