### ISSUE TITLE
An "opened" SpaceLaunchNow instance gets out-of-sync with the actual state of the monitored events

### ISSUE THREAD

**Issue by RockyMtnVideo** [ItsCalebJones/SpaceLaunchNow-Flutter#12]
IOS 13.6; I noticed this issue a few weeks ago, but am just now reporting it.

I am a recent user/supporter, and must open by saying that this is an amazing App (in terms of sheer volume of content, if nothing else).  I started out by simply leaving it open all the time.  What I began to notice was that the Home page statuses would simply get out of sync with the actual statuses of near-term activities.  E.G. launches that had been canceled, would still be counting down, sometimes with bizarre times in their countdown clock.  If I would close the app (swipe it away), and immediately reopen it, all of the information would then be correct.  In short, I no longer keep the app open, when not in use, closing it after each use, and reopening it each time, so that I can count on the details being correct.  It obviously has a background component, because it continues to send messaging about upcoming or ongoing events.  It just seems like those (background) event statuses are not being fed into the open instance of the app itself, so that its display content can stay in sync with event realities.

All of my apps are updated automatically, so I should always have been running the most recent version.  It would be rare that I would not be consistently connected to the network, and have noticed the issues at times that I know, for certain, that I would have been connected for days.

Sorry.  I realize that isn't much to go on.  I have tried to conjure up something/anything that might account for the behavior, but have had no luck with that.

Thanks.

**Comment by ItsCalebJones** [comment]
Hey @RockyMtnVideo - the app does not do any live auto-updating. You should be able to use the 'Refresh' button to do that however.

**Comment by RockyMtnVideo** [comment]
Thanks for the quick response. I had not even noticed it, but I do see it now. Really do love the app. Have a great week.
