### ISSUE TITLE
In-app purchases in SLN 2.3.0 don't work

### ISSUE THREAD

**Issue by beej** [ItsCalebJones/SpaceLaunchNow-Flutter#13]
I just tried tapping all 5 green prices in Space Launch Now version 2.3.0 on my iPhone X running iOS 13.5 and nothing happens when I tap any of them. Restarting the app doesn't help.

**Comment by ItsCalebJones** [comment]
I believe this is the culprit: https://github.com/flutter/flutter/issues/60763

**Comment by ItsCalebJones** [comment]
@beej - the latest update adds an error message popup - could you let me know what error you are getting?

**Comment by beej** [comment]
> could you let me know what error you are getting?

I see no popup in 2.3.1.  It behaves the same way as older versions for me. Any dollar amount I tap appears to do nothing.

**Comment by ItsCalebJones** [comment]
That's - odd. Thanks for the datapoint. For me I get "Cannot connect to iTunes store". 

@derkweijers do you see anything?

**Comment by derkweijers** [comment]
The "confirm your payment" sheet pops-up, I cancel it and I get the "can't connect to iTunes error". After reopening the app, the payment pop-up doesn't even show and it just shows the error.
